apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-migration

resources:
- mtc-operator-sub.yaml
- openshift-migration-ns.yaml
- openshift-migration-operatorgroup.yaml
