apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-migration
  namespace: openshift-migration
spec:
  targetNamespaces:
  - openshift-migration
  namespaces:
  - openshift-migration
